version: '3.8'

services:

  web:
    build: ./
    ports:
      - 8000:8000
    depends_on:
      - db
    command: uv run python main.py

  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
     - /private/var/lib/postgresql:/var/lib/postgresql