"""Initial revision

Revision ID: 6d4f3f2bd099
Revises: 
Create Date: 2025-10-23 20:58:23.486827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d4f3f2bd099'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('parent', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent'], ['activities.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_activities_id'), 'activities', ['id'], unique=False)
    op.create_table('buildings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('latitude', sa.String(), nullable=True),
    sa.Column('longitude', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address')
    )
    op.create_index(op.f('ix_buildings_id'), 'buildings', ['id'], unique=False)
    op.create_table('organisations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('building', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['building'], ['buildings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_organisations_id'), 'organisations', ['id'], unique=False)
    op.create_table('organisation_actvities',
    sa.Column('link_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=True),
    sa.Column('activity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('link_id')
    )
    op.create_index(op.f('ix_organisation_actvities_activity_id'), 'organisation_actvities', ['activity_id'], unique=False)
    op.create_index(op.f('ix_organisation_actvities_organisation_id'), 'organisation_actvities', ['organisation_id'], unique=False)
    op.create_table('organisation_phones',
    sa.Column('phone_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('phone_id'),
    sa.UniqueConstraint('phone')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organisation_phones')
    op.drop_index(op.f('ix_organisation_actvities_organisation_id'), table_name='organisation_actvities')
    op.drop_index(op.f('ix_organisation_actvities_activity_id'), table_name='organisation_actvities')
    op.drop_table('organisation_actvities')
    op.drop_index(op.f('ix_organisations_id'), table_name='organisations')
    op.drop_table('organisations')
    op.drop_index(op.f('ix_buildings_id'), table_name='buildings')
    op.drop_table('buildings')
    op.drop_index(op.f('ix_activities_id'), table_name='activities')
    op.drop_table('activities')
    # ### end Alembic commands ###
