"""Фиксы всех relationship в моделях

Revision ID: aa5aa3debbde
Revises: caeaa5d0a69c
Create Date: 2025-10-23 23:02:44.232192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa5aa3debbde'
down_revision: Union[str, Sequence[str], None] = 'caeaa5d0a69c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
