"""Фикс relationship между Organisation и Building

Revision ID: caeaa5d0a69c
Revises: 6d4f3f2bd099
Create Date: 2025-10-23 22:58:40.409627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caeaa5d0a69c'
down_revision: Union[str, Sequence[str], None] = '6d4f3f2bd099'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organisations', sa.Column('building_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('organisations_building_fkey'), 'organisations', type_='foreignkey')
    op.create_foreign_key(None, 'organisations', 'buildings', ['building_id'], ['id'])
    op.drop_column('organisations', 'building')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organisations', sa.Column('building', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'organisations', type_='foreignkey')
    op.create_foreign_key(op.f('organisations_building_fkey'), 'organisations', 'buildings', ['building'], ['id'])
    op.drop_column('organisations', 'building_id')
    # ### end Alembic commands ###
