"""Обновил relationship у buildings

Revision ID: ecde59255dba
Revises: 04c2b95278e9
Create Date: 2025-10-24 02:34:54.171606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecde59255dba'
down_revision: Union[str, Sequence[str], None] = '04c2b95278e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('buildings_address_key'), 'buildings', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('buildings_address_key'), 'buildings', ['address'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
