class BuildingNotFoundException(Exception): ...
class BuildingWithNoOrganizationsError(Exception): ...
class NoOrganizationsFoundError(Exception): ... # Для ситуаций, когда мы ищем список организаций
class OrganizationNotFoundError(Exception): ... # Для ситуаций, когда мы ищем конкретную организацию
class NoBuildingsFoundError(Exception): ... # Для ситуаций, когда мы ищем список зданий
class ActivityNotFoundError(Exception): ...